# site properties and page defaults
title: BHE-AIM-IMT
subtitle: 
description: Welcome to bhe-aim-imt website! Relying on The Key Laboratory of Brain Health Intelligent Evaluation and Intervention of the Ministry of Education, our lab is dedicated to solving the problem of intelligent audio intervention and contributing to the advancement of the discipline and society. We welcome people from all areas to visit our website to know more about our research achievements, team members and other contents. We look forward to working with you to explore the mysteries of science!

Multimodal Semantic Alignment: This direction focuses on aligning the deep semantics between audio signals and brain signals (e.g., EEG) to provide core support for precise and personalized intelligent interventions. We emphasize exploring cross-modal representation learning, semantic embedding, and alignment techniques, laying a solid foundation for subsequent intervention strategy generation.
Reinforcement Learning: This direction specializes in using reinforcement learning (RL) to dynamically optimize audio intervention strategies, aiming to tailor and adjust the most effective intervention plan in real time for each user. The ultimate goal is to build a closed-loop interactive, continuously learning, and maximally effective intelligent audio intervention system that is both personalized and precise.
Generative Models: This research direction uses advanced generative AI to create new and helpful therapeutic audio. We work with different modern techniques, such as generative adversarial networks (GANs) and diffusion models. Our goal is not only to make the generated audio clear and comfortable to listen to, but also to test and improve its healing effects through scientific methods. We aim to provide practical and new solutions for brain health.

header: images/background_brain.jpg  
footer: images/background.jpg  
proofer: false

# site social media and other links
# 常用网站链接
links:
  bilibili: https://space.bilibili.com/52108001/?spm_id_from=333.999.0.0
  Beijing Institute of Technology: https://www.bit.edu.cn/
  School of Medical Technology: https://smt.bit.edu.cn/
  Key Laboratory of Brain Health Intelligent Evaluation and Intervention of the Ministry of Education: https://bhe-lab.org/

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
